### ISSUE TITLE
Missing vite manifest?

### ISSUE THREAD

**Issue by caseydwyer** [eminos/statamic-group#1]
Hi @eminos! 👋 Thanks for your work on this package; was curious to try it out but ran into this error: 

`Vite manifest not found at A:\laragon\www\test-project\public\vendor\statamic-group\build\manifest.json...`

Possible that the repo needs its JS compiled?

**Comment by eminos** [comment]
Hmm. It should publish the assets automatically after you composer require the package.
Or so I thought. Is that not default in Statamic installations?
Do you have `"@php artisan statamic:install --ansi"` in composer.json -> scripts -> post-autoload-dump?

Nonetheless you can publish the assets with `php artisan vendor:publish --tag=statamic-group`

Maybe that should be in the README...

**Comment by caseydwyer** [comment]
> Hmm. It should publish the assets automatically after you composer require the package. Or so I thought. Is that not default in Statamic installations? Do you have `"@php artisan statamic:install --ansi"` in composer.json -> scripts -> post-autoload-dump?

Yep! That's actually what I was expecting to happen, but for whatever reason, it didn't work. Discovery happens, but no assets are actually published.
![image](https://github.com/eminos/statamic-group/assets/13950848/4d4b23a4-d803-4566-ba44-0c5ec40ec70a)

> Nonetheless you can publish the assets with `php artisan vendor:publish --tag=statamic-group`

This did the trick! I'll close this and defer to you on whether or not you want to dig into the auto-publishing thing more—let me know if there's anything I can do to help. Thanks again!
