### ISSUE TITLE
Field styles are not correctly applied

### ISSUE THREAD

**Issue by tobimori** [eminos/statamic-group#8]
Since updating to v2, my inline groups look like this:
![CleanShot 2023-12-18 at 16 42 36@2x](https://github.com/eminos/statamic-group/assets/29142128/2fbfae65-26f7-4cfa-9aac-eb4fba3213af)

**Comment by eminos** [comment]
Do you mean it's too much padding around the fields?

![image](https://github.com/eminos/statamic-group/assets/1682784/87c21b75-9208-441f-8c29-17296711b774)

**Comment by tobimori** [comment]
It's missing the complete styling, it has the default field title (so it looks borked if it shows the section title) and yeah of course the padding.

**Comment by eminos** [comment]
OH! I see!

**Comment by eminos** [comment]
Fixed in v2.0.1.
